### ISSUE TITLE
Pathway to W3C adoption

### ISSUE THREAD

**Issue by nicksantamaria** [WICG/change-password-url#12]
Hi,

I'm working on implementing the change-password well known URL in Drupal core [(see this issue)](https://www.drupal.org/project/drupal/issues/3018673). 

A maintainer has  asked about the pathway to W3C adoption. They are concerned about the potential of the `/.well-known/change-password` URL changing when formally adopted by the W3C, resulting in Drupal core having to support a legacy URL.

Are you able to advise on the pathway for this standard to be adopted by W3C (if at all)?

Thanks!

**Comment by hober** [comment]
@nicksantamaria It's very unlikely that the URL would change at this point. If we end up changing the scope of the work sufficiently to call for another endpoint, it'll be in addition to, not instead of, this existing URL.

(I'll close this issue as I think that addresses your question to the extent that it can be addressed without a time machine; please do feel free to reopen if you have any followup questions.)

**Comment by marcoscaceres** [comment]
Just from a process perspective (as WICG co-chair), there is a fairly high chance of this graduating to a W3C working group. It depends on implementer interest and us finding a home for the work at either the W3C or WHATWG. I’ll defer to @hober for guidance on when this community feels the spec is ready to graduate.

**Comment by mikewest** [comment]
We discussed this at TPAC, and WebAppSec seems like a good home. I would appreciate @hober or @rmondello following up on the concensus in the room at TPAC (minutes here: https://github.com/w3c/webappsec/blob/master/meetings/2019/2019-09-TPAC-minutes.md#well-knownchange-password) with an email to `public-webappsec@w3.org` asking us to publish the current draft as an FPWD to give folks outside the room a chance to weigh in, and then working with @wseltzer and @samuelweiler to migrate the repo over and publish the draft.
